export const COMPOSIO_META_TOOLS = {
  SEARCH_TOOLS: "COMPOSIO_SEARCH_TOOLS",
  GET_TOOL_SCHEMAS: "COMPOSIO_GET_TOOL_SCHEMAS",
  MANAGE_CONNECTIONS: "COMPOSIO_MANAGE_CONNECTIONS",
  MULTI_EXECUTE_TOOL: "COMPOSIO_MULTI_EXECUTE_TOOL",
  REMOTE_BASH_TOOL: "COMPOSIO_REMOTE_BASH_TOOL",
  REMOTE_WORKBENCH: "COMPOSIO_REMOTE_WORKBENCH",
} as const;

export type ComposioMetaTool =
  (typeof COMPOSIO_META_TOOLS)[keyof typeof COMPOSIO_META_TOOLS];

export const COMPOSIO_TOOL_NAME_PATTERN = "{TOOLKIT}_{ACTION}";

export const COMPOSIO_TOOLKIT_EXAMPLES = [
  "GMAIL_SEND_EMAIL",
  "GOOGLECALENDAR_CREATE_EVENT",
  "GOOGLEDRIVE_SEARCH_FILES",
  "NOTION_CREATE_PAGE",
  "LINEAR_CREATE_ISSUE",
  "GITHUB_CREATE_ISSUE",
  "GOOGLEDOCS_CREATE_DOCUMENT",
  "GOOGLESHEETS_VALUES_UPDATE",
  "STRIPE_CREATE_CUSTOMER",
  "YOUTUBE_LIST_VIDEOS",
  "METAADS_GET_INSIGHTS",
  "GOOGLEADS_LIST_CUSTOMERS",
  "REDDIT_SEARCH_POSTS",
] as const;

const COMPOSIO_META_TOOL_VALUES = new Set<string>(
  Object.values(COMPOSIO_META_TOOLS)
);

export const isComposioMetaTool = (
  toolName: string
): toolName is ComposioMetaTool => COMPOSIO_META_TOOL_VALUES.has(toolName);
